### ISSUE TITLE
Derive Debug for canapi::Error

### ISSUE THREAD

**Issue by elegaanz** [Plume-org/canapi#1]
Otherwise it seems impossible to use `expect` or `unwrap` with them.

**Comment by trinity-1686a** [comment]
You can simply add `#[derive(Debug)]`, default Debug are good enough for most usages
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Fetch("something")', libcore/result.rs:945:5
thread 'main' panicked at 'custom_message: Fetch("something")', libcore/result.rs:945:5

```
